language: python
python:
  - "2.7"
env:
  - DJANGO=1.7
install:
  - pip install coveralls
  - pip install -r requirements/test.txt
script:
  - coverage run --source micorr setup.py test
after_success:
coveralls
