language: python
python:
  - "2.7"
install:
  - pip install coveralls
  - pip install -r requirements/test.txt
script:
  - coverage run --source micorr setup.py test
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - http://micorr.ig.he-arc.ch/dev/pull/
    on_success: always
    on_failure: never
  email:
    recipients:
      - micorr@he-arc.ch
      - cedric@gaspoz-fleiner.com
    on_success: always
    on_failure: always