language: python
python:
  - "2.7"
install:
  - pip install coveralls
  - pip install -r requirements/test.txt
env:
  - DJANGO_SETTINGS_MODULE=config.settings.test

script:
  - coverage run --branch ./manage.py test
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - http://requestb.in/x6amm3x6
      - http://travis.micorr.ultrahook.com
    on_success: always
    on_failure: never
  email:
    recipients:
      - cedric@gaspoz-fleiner.com
      - micorr@he-arc.ch
    on_success: always
    on_failure: always
