version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
  neo4j_data_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=micorr

  neo4j:
    build: ./compose/neo4j
    volumes:
      - neo4j_data_dev:/data
    environment:
      - NEO4J_AUTH=neo4j/secret
    ports:
      - "7474:7474"
      - "7687:7687"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python /app/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres
      - neo4j
    environment:
      - POSTGRES_USER=micorr
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
      - neo4j:neo4j

  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
      - neo4j
    environment:
      - POSTGRES_USER=micorr
    volumes:
      - .:/app
    links:
      - postgres
      - neo4j:neo4j
