version: '2'

volumes:
  postgres_data: {}

services:
  postgres:
    build: ./compose/postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/postgres/backups:/backups
    env_file: .env
    #ports:
    #  - "5432:5432"

  neo4j:
    build: ./compose/neo4j
    restart: always
    volumes:
      - ./data/neo4j:/data


    env_file: .env.neo4j #for setting NEO4J_AUTH var in user/password format
    environment:
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_memory_heap_initial__size=1024M
      - NEO4J_dbms_memory_heap_max__size=1024M
      - NEO4J_ULIMIT_NOFILE=60000
      # to load initial data in neo4j graph.db
      # copy a neo4j-admin dump file to compose/neo4j/initial_neo4j-admin.dump
      # remove it on subsequent builds to avoid overriding data
      - EXTENSION_SCRIPT=/bootstrap_data.sh
      #- EXTENSION_SCRIPT=/backup.sh
    ports:
      - "7474:7474"
      - "7687:7687"

  elasticsearch:
    # we use non official elasticsearch image as elasticsearch only provides docker images version >6.8.2
    # and haystack is not compatible with elasticsearch >2.4
    image: blacktop/elasticsearch:2.4
    environment:
      - cluster.routing.allocation.disk.watermark.low=800mb
      - cluster.routing.allocation.disk.watermark.high=500mb

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    restart: always
    volumes:
      - ./micorr/media:/app/micorr/media
    user: django
    depends_on:
      - postgres
      - redis
      - neo4j
    command: /gunicorn.sh
    env_file: .env


  node:
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile
    restart: always
    depends_on:
      - django

  nginx:
    build:
      context: ./compose/nginx
      dockerfile: Dockerfile.static

    depends_on:
      - django
      - node

    environment:
      # MY_DOMAIN_NAME is used by both nginx (for allowed hosts) and certbot for getting ssl certificate
      # set MY_DOMAIN_NAME env var to eg.: micorr.org in .env
      - MY_DOMAIN_NAME=${MY_DOMAIN_NAME}

    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./data/certs:/etc/nginx/certs
      - ./micorr/media:/media
      - ./data/maintenance:/usr/share/nginx/html


  redis:
    image: redis:latest
