module.exports = function (grunt) {

    require('load-grunt-tasks')(grunt);
    grunt.option('force', true);
    grunt.initConfig({
        babel: {
            options: {
               "plugins": ["transform-es2015-modules-umd"],
                presets: [["env"]], //, {"targets": {"browsers": ["last 2 versions"]}}], "react", "stage-2"],
                sourceMap: true
            },
            dist: {
                files: [
                    {
                        expand: true,
                        cwd: 'micorr/stratigraphies/static/micorr/scripts/ES2015',
                        src: '**/*.js',
                        ext: '.js',
                        dest: 'micorr/stratigraphies/static/micorr/scripts/'
                    }
                ]
            }
        },
	    watch: {
      		scripts: {
        	files: "micorr/stratigraphies/static/micorr/scripts/ES2015/**/*.js",
        	tasks: ["babel"]
		}
      },
        /***
         * browserify test - to use with default CommonJS modules generated by babel v6 (when not using transform-es2015-modules-umd)
         * bundle generated ok but we would still need to adapt rest of angular code
        browserify: {
            dist: {
                files: {
                    'micorr/stratigraphies/static/micorr/scripts/bundle.js': ['micorr/stratigraphies/static/micorr/scripts/business/*.js',
                        'micorr/stratigraphies/static/micorr/scripts/algorithms/*.js', 'micorr/stratigraphies/static/micorr/scripts/utils/*.js',]
                }
            }
        }
         ***/
    });

    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.registerTask("default", ["babel"]);
    //grunt.loadNpmTasks('grunt-browserify');
}


