# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artefacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='author',
            field=models.ManyToManyField(blank=True, help_text=b'The author(s) of this file is (are) responsible for the information provided. Author(s) should provide their last name, initial of their first name and in brackets the abbreviation of their institutional affiliation, such as Degrigny C. (HE-Arc CR).', related_name='artefacts', to='contacts.Contact', verbose_name=b'authors'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='chronology_period',
            field=models.ForeignKey(blank=True, help_text=b'The dating of the artefact', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.ChronologyPeriod', verbose_name=b'dating of artefact (Tpq _ Taq)'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='corrosion_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.CorrosionForm'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='corrosion_type',
            field=models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.CorrosionType'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='environment',
            field=models.ForeignKey(blank=True, help_text=b'The environment where the artefact was found.', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.Environment', verbose_name=b'burial conditions / environment'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='location',
            field=models.ForeignKey(blank=True, help_text=b'The actual location of the artefact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artefacts_locations', to='contacts.Contact', verbose_name=b'artefact location'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='metal1',
            field=models.ForeignKey(blank=True, help_text=b'The primary metal element of the artefact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_metal_artefacts', to='artefacts.Metal', verbose_name=b'1st metal element'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='metalx',
            field=models.ManyToManyField(blank=True, help_text=b'The other metal elements of the artefact.', related_name='other_metal_artefacts', to='artefacts.Metal', verbose_name=b'other metal elements'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='microstructure',
            field=models.ForeignKey(blank=True, help_text=b'A description of the metal: its composition, texture (porosity), hardness, microstructure revealed by etching and specific features (figures and tables are referred as Fig. 1, Table 1)', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.Microstructure'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='origin',
            field=models.ForeignKey(blank=True, help_text=b'The place, city and country where the artefact comes from or the object to which the section considered belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artefacts', to='artefacts.Origin'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='owner',
            field=models.ForeignKey(blank=True, help_text=b'The owner of the artefact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artefacts_owners', to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='recovering_date',
            field=models.ForeignKey(blank=True, help_text=b'The date of excavation for archaeological objects, of production and use for other artefacts', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.RecoveringDate', verbose_name=b'date of recovering'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='responsible_institution',
            field=models.ForeignKey(blank=True, help_text=b'The responsible institution for the artefact sample', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_institution', to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='sample_location',
            field=models.ForeignKey(blank=True, help_text=b'The actual location of the artefact sample', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_location', to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='technology',
            field=models.ForeignKey(blank=True, help_text=b'The manufacturing techniques used to produce the artefact', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.Technology'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='type',
            field=models.ForeignKey(blank=True, help_text=b'The name of the artefact, its typology', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.Type', verbose_name=b'type of artefact'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='user',
            field=models.ForeignKey(blank=True, help_text=b'The user who entered the artefact into the database', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b"user's object"),
        ),
    ]
