# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-02 10:05


from django.db import migrations

"""
replacement for Johan script below:
/* ---! A RÉALISER AVANT LA SUPPRESSION DE LA COLONNE NAME DANS LA TABLE ARTEFACTS_ARTEFACT ET APRÈS LA CRÉATION DE LA TABLE ARTEFACTS_OBJECT !--- */
/* Reprise des noms d'objets depuis la table artefacts_artefact dans la table artefacts_object */
INSERT INTO artefacts_object(id, name, created, modified, user_id) SELECT id, name, created, modified, user_id FROM artefacts_artefact

/* ---! A RÉALISER AVANT LA SUPPRESSION APRÈS LA MIGRATION CRÉANT LA LIAISON ENTRE LES TABLES ARTEFACTS_ARTEFACT ET ARTEFACTS_OBJECT !--- */
/* Jointure entre les objets et les fiches artefact */
UPDATE artefacts_artefact SET object_id = id
"""


# data migration code
def copy_artefact_data_to_object(apps, schema_editor):
    Artefact = apps.get_model('artefacts', 'Artefact')
    Object = apps.get_model('artefacts', 'Object')
    for artefact in Artefact.objects.order_by('id').all():
        # setting object.id to artefact.id should not be necessary todo check if we rely on this anywhere
        object = Object.objects.create(id=artefact.id, name=artefact.name, user=artefact.user)
        object.created = artefact.created
        # object.modified = artefact.modified # overwritten by model auto_now on save. todo see if we can force this
        object.save()
        artefact.object = object
        artefact.save()


# data migration reverse code
def copy_object_data_back_to_artefact(apps, schema_editor):
    """
    name and user fields have just been added back to Artefact field (by reverse migration 0006)
    set back their values from object records.
    Then object table could be safely deleted
    """

    Artefact = apps.get_model('artefacts', 'Artefact')

    for artefact in Artefact.objects.order_by('id').all():
        artefact.name = artefact.object.name
        artefact.user = artefact.object.user
        artefact.save()


class Migration(migrations.Migration):
    dependencies = [
        ('artefacts', '0005_auto_20170511_1934'),
    ]

    operations = [
        migrations.RunPython(copy_artefact_data_to_object, copy_object_data_back_to_artefact)
    ]
