# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-11 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0004_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artefact',
            name='object',
            field=models.ForeignKey(blank=True, help_text=b'The object described by the card', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.Object', verbose_name=b'object described'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='parent',
            field=models.ForeignKey(blank=True, help_text=b'The card from which this card is the child', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_card', to='artefacts.Artefact'),
        ),
    ]
