# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-15 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0006_auto_20170512_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, help_text=b'A field of the artefact card', max_length=200)),
                ('order', models.IntegerField(blank=True, help_text=b'The order of the field', null=True)),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.AlterField(
            model_name='collaboraton_comment',
            name='comment',
            field=models.CharField(blank=True, help_text=b'A comment from the collaborator or author', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collaboraton_comment',
            name='field',
            field=models.ForeignKey(blank=True, help_text=b'The field concerned by the comment', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.Field'),
        ),
    ]
