# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-15 09:42


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0007_auto_20170515_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='order',
            new_name='ordering',
        ),
    ]
