# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-18 12:40


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0009_auto_20170515_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefact',
            old_name='isPublished',
            new_name='published',
        ),
    ]
