# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-22 21:07


from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('artefacts', '0010_auto_20170518_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('object_model_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('field', models.ForeignKey(blank=True, help_text='The field concerned by the comment', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.Field')),
                ('parent', models.ForeignKey(blank=True, help_text='The comment from which this comment is the child', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.Collaboration_comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.RemoveField(
            model_name='collaboraton_comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='collaboraton_comment',
            name='field',
        ),
        migrations.RemoveField(
            model_name='collaboraton_comment',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Collaboraton_comment',
        ),
    ]
