# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-02 12:36
from __future__ import unicode_literals

from django.db import migrations

"""
datamigration replacement for Johan's script_migration_micorr_prod_new_tables.sql extract below:
/* ---! A RÉALISER APRÈS LA CRÉATION DE LA TABLE ARTEFACTS_FIELD !--- */                                       
/* Insertion dans la table artefacts_field pour permettre la collaboration au niveau des champs d'une fiche */ 
INSERT INTO artefacts_field (id, created, modified, name, title) VALUES(nextval('artefacts_field_id_seq'), current_timestamp, current_timestamp, 'Description of artefact', 'descriptionArtefact');
...
"""

initial_field_list = (
    ('Description of artefact', 'descriptionArtefact'),
    ('Type of artefact', 'typeArtefact'),
    ('Origin', 'originArtefact'),
    ('Date of artefact', 'dateArtefact'),
    ('Chronology', 'chronologyArtefact'),
    ('Burial conditions / environment', 'environmentArtefact'),
    ('Artefact location', 'locationArtefact'),
    ('Owner', 'ownerArtefact'),
    ('Inv. Number', 'invNumberArtefact'),
    ('Recorded conservation data', 'recConsDataArtefact'),
    ('Description of sample', 'descriptionSample'),
    ('Alloy', 'alloySample'),
    ('Technology', 'technologySample'),
    ('Lab number of sample', 'labNumberSample'),
    ('Sample location', 'locationSample'),
    ('Responsible institution', 'respInstSample'),
    ('Date and aim of sampling', 'dateAimSamplingSample'),
    ('Stratigraphies', 'stratigraphiesSample'),
    ('Date recovering', 'recoveringDateArtefact')
)


# data migration code
def insert_initial_fields(apps, schema_editor):
    Field = apps.get_model('artefacts', 'Field')
    for field in initial_field_list:
        Field.objects.create(name=field[0], title=field[1])


# data migration reverse_code
def remove_initial_fields(apps, schema_editor):
    Field = apps.get_model('artefacts', 'Field')
    Field.objects.filter(name__in=(f[0] for f in initial_field_list)).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('artefacts', '0012_auto_20170523_1238'),
    ]

    operations = [
        migrations.RunPython(insert_initial_fields, remove_initial_fields)
    ]
