# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-31 15:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0012_datamigration_populate_artefact_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='hidden_by_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='hidden_by_recipient',
            field=models.BooleanField(default=False),
        ),
    ]
