# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-01 20:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0013_auto_20170531_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='comment',
        ),
        migrations.AddField(
            model_name='publication',
            name='comment_delegation',
            field=models.TextField(blank=True, help_text='A comment from the main administrator to the delegated administrator', null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='comment_to_user',
            field=models.TextField(blank=True, help_text='A comment send to the user from the analyzer of the artefact', null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='decision_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='validated',
            field=models.NullBooleanField(default=None),
        ),
    ]
