# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-02 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0014_auto_20170601_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration_comment',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
