# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-02 08:31


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0015_collaboration_comment_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration_comment',
            name='token_for_section',
            field=models.ForeignKey(blank=True, help_text='The token that allow to filter comments for a section from differents tokens', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_for_section', to='artefacts.Token'),
        ),
    ]
