# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-02 16:54


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0016_collaboration_comment_token_for_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration_comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The comment from which this comment is the child', null=True, on_delete=django.db.models.deletion.SET_NULL, to='artefacts.Collaboration_comment'),
        ),
    ]
