# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-09 13:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0017_auto_20170602_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='decision_delegated_user',
            field=models.NullBooleanField(default=None),
        ),
    ]
