# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-19 07:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0018_publication_decision_delegated_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
