# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-19 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0019_publication_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
