# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0022_datamigration_rename_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='city',
            field=models.ForeignKey(blank=True, help_text=b'The city where the artefact was located (optional for objects)', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='site',
            field=models.CharField(blank=True, help_text=b'The place where the artefact was located or the object to which the section considered belongs to', max_length=100, verbose_name=b'site/object'),
        ),
    ]
