# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 14:20


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0024_add_stratigraphy_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='author',
            field=models.ManyToManyField(blank=True, help_text='The author(s) of this file is (are) responsible for the information provided. Author(s) should provide after the abbreviation of their institution affiliation their last name and initial of their first name in brackets such as HE-Arc CR (Degrigny C.). Hold down "Control", or "Command" on a Mac, to select more than one.', related_name='artefacts', to='contacts.Contact', verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='microstructure',
            field=models.ForeignKey(blank=True, help_text='Microstructure of the metal', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.Microstructure'),
        ),
    ]
