# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 20:27


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0025_artefacts_author_and_microstructure_fields_help_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratigraphy',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The section in which the stratigraphy is displayed', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.Section'),
        ),
    ]
