# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 22:41


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0026_stratigraphy_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='author',
            field=models.ManyToManyField(blank=True, help_text='The author(s) of this file is (are) responsible for the information provided. Author(s) should provide after the abbreviation of their institution affiliation their last name and initial of their first name in brackets such as HE-Arc CR (Degrigny C.). Hold down "Control", or "Command" on a Mac, to select more than one', related_name='artefacts', to='contacts.Contact', verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='corrosion_form',
            field=models.ForeignKey(blank=True, help_text='Based on observation', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.CorrosionForm'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='corrosion_type',
            field=models.ForeignKey(blank=True, help_text='Based on literature', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.CorrosionType'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='environment',
            field=models.ForeignKey(blank=True, help_text='The environment where the artefact was found', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.Environment', verbose_name='burial conditions / environment'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='metalx',
            field=models.ManyToManyField(blank=True, help_text='The other metal elements of the artefact, several elements can be selected by clicking on Ctrl + elements selected', related_name='other_metal_artefacts', to='artefacts.Metal', verbose_name='other metal elements'),
        ),
    ]
