# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-18 15:43


from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0027_artefact_help_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('page_template', models.IntegerField(default=1, help_text='Page template identifier')),
                ('title', models.CharField(blank=True, default='', help_text='The section title', max_length=100)),
                ('fieldset', models.CharField(blank=True, default='', help_text='Name of the Form fieldset associated with the section (if any)', max_length=50)),
                ('is_fieldset_first', models.BooleanField(default=False, help_text='If true fieldset displayed before images and stratigraphies in section')),
                ('order', models.IntegerField(default=1, help_text='The order of the section in page template')),
                ('has_content', models.BooleanField(default=False)),
                ('content_help_text', models.TextField(blank=True, default='', help_text='Help text of content for author')),
                ('has_complementary_information', models.BooleanField(default=False)),
                ('complementary_information_help_text', models.TextField(blank=True, default='', help_text='Help text of complementary information for author')),
                ('has_images', models.BooleanField(default=False)),
                ('images_help_text', models.TextField(blank=True, default='', help_text='Help text of complementary information for author')),
                ('has_stratigraphies', models.BooleanField(default=False)),
                ('stratigraphies_help_text', models.TextField(blank=True, default='', help_text='Help text of stratigraphies for author')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Section Template',
                'verbose_name_plural': 'Section Templates',
            },
        ),
        migrations.AddField(
            model_name='sectioncategory',
            name='page_template',
            field=models.IntegerField(default=1, help_text='Page template identifier'),
        ),
        migrations.AlterField(
            model_name='sectioncategory',
            name='name',
            field=models.CharField(choices=[('AR', 'Artefact'), ('DE', 'Description'), ('SA', 'Sample'), ('AN', 'Analysis and Results'), ('SY', 'Synthesis'), ('CO', 'Conclusion'), ('RE', 'References')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='sectioncategory',
            unique_together=set([('page_template', 'name'), ('page_template', 'order')]),
        ),
        migrations.AddField(
            model_name='sectiontemplate',
            name='section_category',
            field=models.ForeignKey(blank=True, help_text='The corresponding section category', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.SectionCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='sectiontemplate',
            unique_together=set([('page_template', 'order')]),
        ),
    ]
