# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0029_datamigration_page_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='template',
            field=models.ForeignKey(blank=True, default=None, help_text=b'The Section template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='artefacts.SectionTemplate'),
        ),
    ]
