# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 10:13
from __future__ import unicode_literals

from django.db import migrations

def update_sections(apps, schema_editor):
    """
    Update existing Sections's template foreign keys based on section/section template order field
    (before removing redundant columns from Section records in subsequent migration)
    :param apps:
    :param schema_editor:
    :return:
    """
    Section = apps.get_model('artefacts', 'Section')
    SectionTemplate = apps.get_model('artefacts', 'SectionTemplate')

    st_order_pk_map = dict(SectionTemplate.objects.filter(page_template=1).values_list('order','pk'))
    for order,st_pk in st_order_pk_map.items():
        Section.objects.filter(order=order).update(template_id=st_pk)

def nop_reverse_migration(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0030_section_template'),
    ]

    operations = [
        migrations.RunPython(update_sections, nop_reverse_migration)
    ]
