# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0032_remove_section_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=80)),
                ('field', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtefactFormDescription',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('artefacts.formdescription',),
        ),
    ]
