# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-26 13:41
from __future__ import unicode_literals

from collections import OrderedDict

from django.db import migrations

CHRONOLOGY_CATEGORY_TPQ_TAQ = OrderedDict((
    (u'Bronze Age', {'tpq': -3300, 'taq': -1200}),
    (u'Early Bronze Age', {'tpq': -3300, 'taq': -2100}),
    (u'Middle Bronze Age', {'tpq': -2100, 'taq': -1550}),
    ('Late Bronze Age', {'tpq': -1550, 'taq': -1200}),
    ('Iron Age', {'tpq': -1200, 'taq': -550}),
    ('Roman Times', {'tpq': -1200, 'taq': 453}),
    ('Medieval times', {'tpq': 500, 'taq': 1500}),
    ('Early medieval times', {'tpq': 500, 'taq': 1000}),
    ('High medieval times', {'tpq': 1000, 'taq': 1250}),
    ('Late medieval times', {'tpq': 1250, 'taq': 1500}),
    ('Modern Times', {'tpq': 1500, 'taq': 1800}),
    ('First World War', {'tpq': 1914, 'taq': 1918}),
    ('Questionable', {'tpq': 0, 'taq': 0})))

CHRONOLOGY_PERIOD_TPQ_TAQ = {u'14th Century BC, Bronze Age D': {'tpq': -140, 'taq': -1300},
                             u'1550BC _ 1350BC': {'tpq': -1550, 'taq': -1350},
                             u'16th century AD': {'tpq': 1501, 'taq': 1600},
                             u'1720 AD': {'tpq': 1720, 'taq': 0},
                             u'1780': {'tpq': 1780, 'taq': 0},
                             u'17th Century AD': {'tpq': 1601, 'taq': 1700},
                             u'1860 _ 1896': {'tpq': 1860, 'taq': 1896},
                             u'1900 AD/20th century': {'tpq': 1900, 'taq': 2000},
                             u'1902 _ 1904': {'tpq': 1902, 'taq': 1904},
                             u'1909 _ 1910': {'tpq': 1909, 'taq': 1910},
                             u'1915': {'tpq': 1915, 'taq': 0},
                             u'1918': {'tpq': 1918, 'taq': 0},
                             u'1970 _ 1974': {'tpq': 1970, 'taq': 1974},
                             u'19th - 20th century': {'tpq': 1801, 'taq': 2000},
                             u'1st century AD': {'tpq': 1, 'taq': 100},
                             u'20 BC _ 50 AC': {'tpq': -20, 'taq': 50},
                             u'20th century (1986 _ 1990)': {'tpq': 1986, 'taq': 1990},
                             u'2nd half 1st century AD.': {'tpq': 50, 'taq': 100},
                             u'550 _ 650 AD': {'tpq': 550, 'taq': 650},
                             u'550 _ 750 AD': {'tpq': 550, 'taq': 750},
                             u'5th Century BC': {'tpq': -500, 'taq': -401},
                             u'August style: First century after Christ': {'tpq': 1, 'taq': 100},
                             u'Augustus style: 1th century A.D.': {'tpq': 1, 'taq': 100},
                             u'Augustus style: 1th century AD': {'tpq': 1, 'taq': 100},
                             u'Augustus style: First century after Christ': {'tpq': 1,
                                                                             'taq': 100},
                             u'Before 1500 A.D (if original), 20th century (if replica)': {'tpq': 0,
                                                                                           'taq': 1500},
                             u'Between 1000 and 650 years BC (if original) or 20th century (if fake)': {'tpq': -1000,
                                                                                                        'taq': -650},
                             u'Between 200 at 1300 AD': {'tpq': 200, 'taq': 1300},
                             u'Bronze Age': {'tpq': -3300, 'taq': -600},
                             u'Hallstatt A/B (1050BC _ 800BC)': {'tpq': -1050,
                                                                 'taq': -800},
                             u'Hallstatt A2/B (1050BC _ 800BC)': {'tpq': -1050,
                                                                  'taq': -800},
                             u'Hallstatt B1 (1054/1037BC _ 1000BC)': {'tpq': -1054,
                                                                      'taq': -1000},
                             u'Hallstatt B2/3 (1000BC _ not defined)': {'tpq': -1000,
                                                                        'taq': 0},
                             u'La T\xe8ne C, 250 _ 140 BC': {'tpq': -250, 'taq': -140},
                             u'La T\xe8ne D (140BC _ 30BC)': {'tpq': -140, 'taq': -30},
                             u'Probably from the latest period of Ancient Egypt.': {'tpq': -664,
                                                                                    'taq': -332},
                             u'Roman Times': {'tpq': -753, 'taq': 476},
                             u'Second half of the 2nd Century AD (150 _ 200 AD)': {'tpq': 150, 'taq': 200},
                             u'TPQ: unknown, TAQ: 1500': {'tpq': 0, 'taq': 1500},
                             u'Tpq (earliest): unknown, Taq (latest): 1500': {'tpq': 0, 'taq': 1500},
                             u'Unknown': {'tpq': 0, 'taq': 0},
                             u'before 1500': {'tpq': 0, 'taq': 1500},
                             u'mideval times': {'tpq': 500, 'taq': 1500}}


def convert_chronology_periods(apps, schema_editor):
    ChronologyPeriod = apps.get_model('artefacts', 'ChronologyPeriod')
    ChronologyCategory = apps.get_model('artefacts', 'ChronologyCategory')

    # update existing categories
    for cc in ChronologyCategory.objects.all():
        if cc.name in CHRONOLOGY_CATEGORY_TPQ_TAQ:
            cc.tpq = CHRONOLOGY_CATEGORY_TPQ_TAQ[cc.name]['tpq']
            cc.taq = CHRONOLOGY_CATEGORY_TPQ_TAQ[cc.name]['taq']
            cc.order = CHRONOLOGY_CATEGORY_TPQ_TAQ.keys().index(cc.name)
            cc.save()

    # add missing categories
    for name in CHRONOLOGY_CATEGORY_TPQ_TAQ.iterkeys():
        if not ChronologyCategory.objects.filter(name=name).exists():
            new_cc = ChronologyCategory.objects.create(name=name, order=CHRONOLOGY_CATEGORY_TPQ_TAQ.keys().index(name),
                                                       **CHRONOLOGY_CATEGORY_TPQ_TAQ[name])
            print('\nadded {} : {} => ChronologyCategory({}) '.format(name, CHRONOLOGY_CATEGORY_TPQ_TAQ[name], new_cc.id))

    for cp in ChronologyPeriod.objects.all():
        print('converting {} -> {} artefact(s)'.format(cp.name, cp.artefact_set.count()))
        for a in cp.artefact_set.all():
            if cp.name in CHRONOLOGY_PERIOD_TPQ_TAQ:
                a.chronology_tpq = CHRONOLOGY_PERIOD_TPQ_TAQ[cp.name]['tpq']
                a.chronology_taq = CHRONOLOGY_PERIOD_TPQ_TAQ[cp.name]['taq']
            else:
                print('\nChronologyPeriod({}) : "{}" missing in CHRONOLOGY_PERIOD_TPQ_TAQ\n'.format(cp.id, cp.name))
            a.chronology_category = cp.chronology_category
            a.chronology_comment = cp.name
            a.save()

def nop_reverse_migration(apps, schema_editor):
    pass



class Migration(migrations.Migration):
    dependencies = [
        ('artefacts', '0035_add_chronology_fields'),
    ]

    operations = [
        migrations.RunPython(convert_chronology_periods, nop_reverse_migration)
    ]
