# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-29 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0036_datamigration_chronology_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('symbol', models.CharField(help_text=b'Symbol of the element', max_length=2)),
                ('name', models.CharField(help_text=b'Name of the element', max_length=50)),
                ('phase', models.CharField(blank=True, help_text=b'Natural phase of the element at room temperature', max_length=10)),
                ('category', models.CharField(blank=True, help_text=b'Category of the element', max_length=50)),
                ('number', models.IntegerField(help_text=b'Atomic number of the element')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AlterModelOptions(
            name='artefact',
            options={'ordering': ['metal1', 'alloy', 'chronology_category', 'type'], 'verbose_name': 'Artefact', 'verbose_name_plural': 'Artefacts'},
        ),
        migrations.AlterField(
            model_name='artefact',
            name='chronology_period',
            field=models.ForeignKey(blank=True, editable=False, help_text=b'The dating of the artefact', null=True, on_delete=django.db.models.deletion.CASCADE, to='artefacts.ChronologyPeriod', verbose_name=b'dating of artefact (Tpq _ Taq)'),
        ),
    ]
