# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-29 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0038_datamigration_init_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='metal_e_1',
            field=models.ForeignKey(blank=True, help_text=b'The primary metal element of the artefact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_metal_artefacts', to='artefacts.Element', verbose_name=b'first metal element'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='metal_e_x',
            field=models.ManyToManyField(blank=True, help_text=b'The other metal elements of the artefact, several elements can be selected by clicking on Ctrl + elements selected', related_name='other_metal_artefacts', to='artefacts.Element', verbose_name=b'other metal elements'),
        ),
    ]
