# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-29 21:09
from __future__ import unicode_literals

from django.db import migrations


def copy_metal_2_element(apps, schema_editor):
    Element = apps.get_model('artefacts', 'Element')
    Artefact = apps.get_model('artefacts', 'Artefact')

    for a in Artefact.objects.all():
        if a.metal1:
            a.metal_e_1 = Element.objects.get(symbol=a.metal1.element)
            a.save()
        if a.metalx.count():
            a.metal_e_x.add(*[Element.objects.get(symbol=m.element) for m in a.metalx.all()])
            a.save()


def nop_reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('artefacts', '0039_add_element_foreign_keys'),
    ]

    operations = [
        migrations.RunPython(copy_metal_2_element, nop_reverse_migration),
    ]
