# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-30 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0040_datamigration_metal_to_element'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artefact',
            options={'ordering': ['metal_e_1', 'alloy', 'chronology_category', 'type'], 'verbose_name': 'Artefact', 'verbose_name_plural': 'Artefacts'},
        ),
        migrations.RemoveField(
            model_name='artefact',
            name='metal1',
        ),
        migrations.RemoveField(
            model_name='artefact',
            name='metalx',
        ),
    ]
