# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 14:27


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0041_remove_metal1_and_metalx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metal',
        ),
    ]
