# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 15:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0042_delete_metal'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='credit',
            field=models.CharField(blank=True, help_text='Identifies the copyright holder of the image', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='credit_url',
            field=models.CharField(blank=True, help_text='Optional URL associated with the credit line', max_length=500),
        ),
    ]
