# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 15:34
from __future__ import unicode_literals

from django.db import migrations

import re

def extract_credit_from_legend(apps, schema_editor):
    Image = apps.get_model('artefacts', 'Image')
    for im in Image.objects.filter(legend__contains='credit'):
        m = re.search('(.*)credit.(.*)', im.legend)
        if m:
            im.legend = m.group(1)
            im.credit = m.group(2)
            print('{} credit: {}'.format(im.pk,im.credit))
            im.save()


def nop_reverse_migration(apps, schema_editor):
    pass
    # Image = apps.get_model('artefacts', 'Image')
    # for im in Image.objects.filter(credit='credit'):



class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0043_add_image_credit'),
    ]

    operations = [
        migrations.RunPython(extract_credit_from_legend, nop_reverse_migration),
    ]
