# Generated by Django 3.0.7 on 2021-08-25 23:56

import artefacts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0046_auto_20200113_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratigraphy',
            name='colourFamily',
            field=models.CharField(default='colourFamily', max_length=100),
        ),
        migrations.AddField(
            model_name='stratigraphy',
            name='observationMode',
            field=models.CharField(choices=[('BI', 'Binocular'), ('CS', 'Cross section')], default='BI', max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, help_text='The image file', max_length=200, null=True, upload_to=artefacts.get_img_storage_path),
        ),
    ]
