# Generated by Django 3.0.7 on 2021-09-22 14:52

import artefacts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0047_add_stratigraphy_observation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='right',
            field=models.CharField(choices=[('R', 'Read only'), ('W', 'Read and comment'), ('E', 'Edit (Read/Write)')], default='R', max_length=1),
        )
    ]
