# Generated by Django 3.0.14 on 2021-12-09 17:35

import artefacts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0050_datamigration_add_new_page_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdescription',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, help_text='The image file', null=True, upload_to=artefacts.get_img_storage_path),
        ),
    ]
