# Generated by Django 3.0.14 on 2021-12-09 17:38

from django.db import migrations

# ARTEFACT_FIELDS_METADATA = [{'field': f.name, 'name':f.verbose_name, 'text':f.help_text} for f in Artefact._meta.fields ]
ARTEFACT_FIELDS_METADATA = [
    {'field': 'id', 'name': 'ID', 'text': ''},
    {'field': 'created', 'name': 'created', 'text': ''},
    {'field': 'modified', 'name': 'modified', 'text': ''},
    {'field': 'name', 'name': 'Artefact name', 'text': '', 'instructions': 'The name should be specific to the object studied: short but informative to avoid confusion between similar objects (indication of a site, collection, etc.).'},
    {'field': 'author', 'name': 'authors',
     'text': 'The author(s) of this file is (are) responsible for the information provided.',
     'instructions': '''All the affiliated authors have to be named. The principal author’s name comes first. The supervisor’s name of a student comes last. See whether you are in the list provided. Otherwise add your institution or name: If you represent an institution: Institution (author family name first initial of first name.), city of the institution, canton or state, country of the institution. Example: Museum of corrosion (Uster M.), Neuchâtel, Switzerland If you are an individual: author first name and family name, city, canton or state, country. Example: Marie Uster, Neuchâtel, Neuchâtel, Switzerland Hold on “Control” to put more than one name.'''},
    {'field': 'description',
     'name': 'description of artefact',
     'text': 'A short description of the artefact.)',
     'instructions': 'The description can also include its general appearance (colour, presence or not of a corrosion layer, missing parts, large cracks, etc.) and dimensions.'},
    {'field': 'inventory_number',
     'name': 'inv. Number',
     'text': 'The inventory number of the artefact',
     'instructions':''},
    {'field': 'recorded_conservation_data',
     'name': 'recorded conservation data',
     'text': 'A brief description of the conservation treatment applied',
     'instructions':'If any add literature references (Names of authors, year). If conservation data is not available, type N/A.'},
    {'field': 'sample_description',
     'name': 'description of sample',
     'text': 'Information on the sample, the way it was obtained, its condition (presence or not of corrosion layers) and dimensions',
     'instructions':''},
    {'field': 'sample_number',
     'name': 'lab number of sample',
     'text': 'The inventory number of the artefact sample',
     'instructions':''},
    {'field': 'date_aim_sampling',
     'name': 'date and aim of sampling',
     'text': 'The date and aim of sampling',
     'instructions':''},
    {'field': 'validated', 'name': 'validated', 'text': '',
     'instructions':''},
    {'field': 'published', 'name': 'published', 'text': '',
     'instructions':''},
    #
    # {'field': 'object',
    #  'name': 'object described',
    #  'text': 'Name of the artefact',
    #  'instructions': 'The name should be specific to the object studied: short but informative to avoid confusion between similar objects (indication of a site, collection, etc.).'},
    {'field': 'metal_e_1',
     'name': 'first metal element',
     'text': 'The primary metal element of the artefact',
     'instructions':'Type the chemical designation of the element in the empty box. it will show up. Select it and insert it in the box.'},
    {'field': 'alloy',
     'name': 'alloy',
     'text': 'The alloy the artefact is made of',
     'instructions':'Type your text in the empty box. If the alloy already exists, it will show up. If not, you can create a new origin which will be saved.'},
    {'field': 'type',
     'name': 'type of artefact',
     'text': 'The typology of the artefact',
     'instructions':'Type your text in the empty box. If the type already exists, it will show up. If not, you can create a new type which will be saved.'},

    {'field': 'origin',
     'name': 'origin',
     'text': 'The place, city and country where the artefact comes from or the object to which the section considered belongs to',
     'instructions':'Scroll through the existing options using the arrow. If none of the options are suitable, you can create a new origin which by clicking on “+” and fill in the required information.'
     },
    {'field': 'recovering_date',
     'name': 'date of recovering',
     'text': 'The date of excavation for archaeological objects, of production and use for other artefacts',
     'instructions':'Type your text in the empty box. If the date already exists, it will show up. If not, you can create a new type which will be saved. If recovering date is unkown, select “unknown”.'},
    {'field': 'chronology_category',
     'name': 'chronology category',
     'text': 'A general dating of the artefact',
     'instructions':'Type your text in the empty box. If the chronology category already exists, it will show up. If not, you can create a new origin which will be saved.'},

    {'field': 'chronology_tpq',
     'name': 'chronology tpq',
     'text': 'Dating of artefact TPQ (Terminus post quem) e.g. "3000 B.C."',
     'instructions':''},
    {'field': 'chronology_taq',
     'name': 'chronology taq',
     'text': 'Dating of artefact TAQ (Terminus ante quem) e.g. "200 A.D."',
     'instructions':''},
    {'field': 'chronology_comment',
     'name': 'chronology comment',
     'text': 'Dating of artefact comment',
     'instructions':'Any additional information about the datation. If datation is questionable, please state it here.'},
    {'field': 'environment',
     'name': 'burial conditions / environment',
     'text': 'The environment where the artefact was found'},
    {'field': 'location',
     'name': 'artefact location',
     'text': 'The actual location of the artefact',
     'instructions':'Scroll through the existing options using the arrow. If none of the options are suitable, you can create a new origin which by clicking on “+” and fill in the required information.'},
    {'field': 'owner', 'name': 'owner', 'text': 'The owner of the artefact',
     'instructions':'Scroll through the existing options using the arrow. If none of the options are suitable, you can create a new origin which by clicking on “+” and fill in the required information.'},
    {'field': 'technology',
     'name': 'technology',
     'text': 'The manufacturing techniques used to produce the artefact',
     'instructions':'Type your text in the empty box. If the technology already exists, it will show up. If not, you can create a new origin which will be saved. If the technology is unkown, select “unknown”.'},
    {'field': 'sample_location',
     'name': 'sample location',
     'text': 'The actual location of the artefact sample',
     'instructions':'Scroll through the existing options using the arrow. If none of the options are suitable, you can create a new origin which by clicking on “+” and fill in the required information.'},
    {'field': 'responsible_institution',
     'name': 'responsible institution',
     'text': 'The responsible institution for the artefact sample',
     'instructions':'Scroll through the existing options using the arrow. If none of the options are suitable, you can create a new origin which by clicking on “+” and fill in the required information.'},
    {'field': 'microstructure',
     'name': 'microstructure',
     'text': 'The microstructure of the metal',
     'instructions':'Type your text in the empty box. If the microstructure already exists, it will show up. If not, you can create a new type which will be saved.'},
    {'field': 'corrosion_form',
     'name': 'corrosion form',
     'text': 'Based on observation',
     'instructions':'Type your text in the empty box. If the corrosion form already exists, it will show up. If not, you can create a new corrosion form which will be saved.'},
    {'field': 'corrosion_type',
     'name': 'corrosion type',
     'text': 'Based on literature',
     'instructions':'Type your text in the empty box. If the corrosion type already exists, it will show up. If not, you can create a new corrosion form which will be saved.'},
    {'field': 'parent',
     'name': 'parent',
     'text': 'The card from which this card is the child',
     'instructions':''}]


def add_artefactform_descriptions(apps, schema_editor):
    ArtefactFormDescription = apps.get_model('artefacts', 'ArtefactFormDescription')
    for rec in ARTEFACT_FIELDS_METADATA:
        ArtefactFormDescription.objects.update_or_create(form='ArtefactForm', field=rec.pop('field'), defaults=rec)


def remove_artefactform_descriptions(apps, schema_editor):
    ArtefactFormDescription = apps.get_model('artefacts', 'ArtefactFormDescription')
    ArtefactFormDescription.objects.filter(form='ArtefactForm',
                                           field__in=[r['field'] for r in ARTEFACT_FIELDS_METADATA]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0051_artefactfromdescription_instructions'),
    ]

    operations = [
        migrations.RunPython(add_artefactform_descriptions, remove_artefactform_descriptions)
    ]
