# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.blocks.static_block
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamfieldPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title', template=b'documents/blocks/heading.html')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'rawparagraph', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'video', wagtail.wagtailembeds.blocks.EmbedBlock()), (b'figure', wagtail.wagtailcore.blocks.StreamBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'video', wagtail.wagtailembeds.blocks.EmbedBlock()), (b'meta', wagtail.wagtailcore.blocks.StructBlock([(b'fignum', wagtail.wagtailcore.blocks.IntegerBlock()), (b'legend', wagtail.wagtailcore.blocks.TextBlock()), (b'credit', wagtail.wagtailcore.blocks.CharBlock())]))], icon=b'cogs')), (b'animation', wagtail.wagtailcore.blocks.static_block.StaticBlock(admin_text=b'Default tour animation: no configuration needed.', template=b'documents/blocks/animation.html'))])),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
