# Generated by Django 3.0.5 on 2020-06-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200611_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsindex',
            name='top_news_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.NewsItem'),
        ),
    ]
