# Generated by Django 3.0.7 on 2021-08-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_newsindex_top_news_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsindex',
            name='top_news_item',
            field=models.ForeignKey(blank=True, help_text='The selected news items is published on MiCorr home page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.NewsItem'),
        ),
    ]
