# -*- coding: utf-8 -*-

# Generated by Django 1.10.2 on 2016-10-19 14:15


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import django_extensions.db.fields


class Migration(migrations.Migration):


    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('organization_name', models.CharField(blank=True, default='', help_text='Name of the organization (leave empty if this is an individual contact.', max_length=250, verbose_name='organization name')),
                ('organization_complement', models.CharField(blank=True, default='', help_text='Complement of the organization name (could be a department, ... Leave empty if this is an individual contact.', max_length=250, verbose_name='organization complement')),
                ('name', models.CharField(blank=True, default='', help_text='Name of the individual or the contact (in case of an organization contact).', max_length=250, verbose_name='name')),
                ('middle_name', models.CharField(blank=True, default='', help_text='Middle name of the individual or the contact (in case of an organization contact).', max_length=50, verbose_name='middle name')),
                ('surname', models.CharField(blank=True, default='', help_text='Surname of the individual or the contact (in case of an organization contact).', max_length=250, verbose_name='surname')),
                ('address_line_1', models.CharField(blank=True, default='', help_text='First line of the address.', max_length=250, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, default='', help_text='Second line of the address.', max_length=250, verbose_name='address line 2')),
                ('address_line_3', models.CharField(blank=True, default='', help_text='Third line of the address.', max_length=250, verbose_name='address line 3')),
                ('zip_code', models.CharField(blank=True, default='', help_text='Zip code of the city.', max_length=250, verbose_name='zip code')),
                ('url', models.URLField(blank=True, help_text='URL of the personal or organization website.', max_length=250, null=True, verbose_name='url')),
                ('email', models.EmailField(blank=True, help_text='Email address.', max_length=250, null=True, verbose_name='email')),
                ('fon', models.CharField(blank=True, default='', help_text='Enter the number in the format: +41 32 930 2088 (without dashes or non numerical characters).', max_length=20, verbose_name='fon number')),
                ('mobile', models.CharField(blank=True, default='', help_text='Enter the number in the format: +41 79 930 2088 (without dashes or non numerical characters).', max_length=20, verbose_name='mobile fon number')),
                ('city', models.ForeignKey(blank=True, help_text='City (from geo database)', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='city')),
                ('country', models.ForeignKey(blank=True, help_text='Country (from geo database)', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country', verbose_name='country')),
                ('parent', models.ForeignKey(blank=True, help_text='Specify one parent to create dependencies between contacts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='contacts.Contact', verbose_name='parent')),
                ('region', models.ForeignKey(blank=True, help_text='Region or state (from geo database)', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region', verbose_name='region/state')),
                ('user', models.OneToOneField(blank=True, help_text="If this contact is also a user, it's user account.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['organization_name', 'name', 'surname'],
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
