# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=80, null=True)),
                ('uid', models.CharField(blank=True, max_length=80, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FamilyDescription',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stratigraphies.nodedescription',),
        ),
        migrations.CreateModel(
            name='FamilyGroupDescription',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stratigraphies.nodedescription',),
        ),
    ]
