# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratigraphies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedescription',
            name='label',
            field=models.CharField(default='Family', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodedescription',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nodedescription',
            name='uid',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
